server:
  port: 8761
eureka:
  client:
    register-with-eureka: false #??????Eureka????
    fetch-registry: false #??Eureka?????????????
  instance:
    preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
security:
  basic:
