#????
server:
  port: 8002
#????
spring:
  application:
    name: consumer
#eureka??
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
  instance:
    preferIpAddress: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


